import{a as L,i as p,S as b}from"./assets/vendor-89feecc5.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const v=document.querySelector(".form"),y=document.querySelector(".gallery"),c=document.querySelector("span"),o=document.querySelector('button[data-action="load-more"]'),w=L.create({baseURL:"https://pixabay.com/api/",params:{key:"41516646-ec27055f09ddd37d9bfda39a5",image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:40}});function m(s){p.error({message:`❌ Sorry, ${s}`,icon:"",position:"topRight"})}function f(s){s.classList.remove("visibility")}function i(s){s.classList.add("visibility")}const S=async s=>{try{return(await w.get("",{params:s})).data}catch(t){i(c),m(t)}},k=s=>{let t=1,n=!1;const a=40;return async()=>{try{if(n)return[];const{hits:e,totalHits:r}=await S({page:t,q:s});return f(o),t>=Math.ceil(r/a)&&Math.ceil(r/a)!==0&&(n=!0,i(o),p.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),t+=1,e}catch(e){i(c),i(o),m(e)}}};let u=null;v.addEventListener("submit",async s=>{s.preventDefault();let t=!1;u!=null&&(o.removeEventListener("click",u),u=null);const a=new FormData(s.currentTarget).get("search"),e=k(a);y.innerHTML="",u=async()=>{if(i(o),f(c),await M(e()),t){const r=()=>{const d=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:d*2,behavior:"smooth"})};o.addEventListener("click",r())}return t=!0,i(c),t},await u(),o.addEventListener("click",u)});async function M(s){try{const t=await s;if(f(c),!t.length){p.error({message:"❌ Sorry, there are no images matching your search query. Please, try again!",icon:"",position:"topRight"}),i(c),i(o);return}const n=new b(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom"}),a=I(t);y.insertAdjacentHTML("beforeend",a),n.refresh()}catch(t){i(c),i(o),m(t)}}function I(s){return s.reduce((n,{webformatURL:a,largeImageURL:e,tags:r,likes:l,views:d,comments:g,downloads:h})=>n+`<li class="gallery-item">
    <a class="gallery-link" href="${e}">
        <img class="gallery-image" src="${a}" alt="${r}"/>
    </a>
    <ul class="characteristics-list">
    <li class="characteristics"><span class="characteristics-titel">Likes</span> <span>${l}</span></li>
    <li class="characteristics"><span class="characteristics-titel">Views</span> <span>${d}</span></li>
    <li class="characteristics"><span class="characteristics-titel">Comments</span> <span>${g}</span></li>
    <li class="characteristics"><span class="characteristics-titel">Downloads</span> <span>${h}</span></li>
</ul>
    
</li>`,"")}
//# sourceMappingURL=commonHelpers.js.map
