import{a as g,i as u,S as h}from"./assets/vendor-89feecc5.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerpolicy&&(s.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?s.credentials="include":e.crossorigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const L=document.querySelector(".form"),p=document.querySelector(".gallery"),o=document.querySelector("span"),c=document.querySelector('button[data-action="load-more"]'),b=g.create({baseURL:"https://pixabay.com/api/",params:{key:"41516646-ec27055f09ddd37d9bfda39a5",image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:40}});function y(i){u.error({message:`❌ Sorry, ${i}`,icon:"",position:"topRight"})}const v=async i=>{try{return(await b.get("",{params:i})).data}catch(t){o.classList.add("visibility"),y(t)}},w=i=>{let t=1,r=!1;const a=40;return async()=>{try{if(r)return[];const{hits:e,totalHits:s}=await v({page:t,q:i});return c.classList.remove("visibility"),t>=Math.ceil(s/a)&&Math.ceil(s/a)!==0&&(r=!0,c.classList.add("visibility"),u.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),t+=1,e}catch(e){o.classList.add("visibility"),c.classList.add("visibility"),y(e)}}};let l=null;L.addEventListener("submit",async i=>{i.preventDefault();let t=!1;l!=null&&(c.removeEventListener("click",l),l=null);const a=new FormData(i.currentTarget).get("search"),e=w(a);p.innerHTML="",l=async()=>{if(c.classList.add("visibility"),o.classList.remove("visibility"),await S(e()),t){const s=()=>{const d=document.querySelector(".gallery-item").getBoundingClientRect().height;console.log(d),window.scrollBy({top:d*2,behavior:"smooth"})};c.addEventListener("click",s())}return t=!0,o.classList.add("visibility"),t},await l(),c.addEventListener("click",l)});async function S(i){try{const t=await i;if(o.classList.remove("visibility"),!t.length){u.error({message:"❌ Sorry, there are no images matching your search query. Please, try again!",icon:"",position:"topRight"}),o.classList.add("visibility"),c.classList.add("visibility");return}const r=new h(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom"}),a=k(t);p.insertAdjacentHTML("beforeend",a),r.refresh()}catch(t){o.classList.add("visibility"),c.classList.add("visibility"),y(t)}}function k(i){return i.reduce((r,{webformatURL:a,largeImageURL:e,tags:s,likes:n,views:d,comments:m,downloads:f})=>r+`<li class="gallery-item">
    <a class="gallery-link" href="${e}">
        <img class="gallery-image" src="${a}" alt="${s}"/>
    </a>
    <ul class="characteristics-list">
    <li class="characteristics"><span class="characteristics-titel">Likes</span> <span>${n}</span></li>
    <li class="characteristics"><span class="characteristics-titel">Views</span> <span>${d}</span></li>
    <li class="characteristics"><span class="characteristics-titel">Comments</span> <span>${m}</span></li>
    <li class="characteristics"><span class="characteristics-titel">Downloads</span> <span>${f}</span></li>
</ul>
    
</li>`,"")}
//# sourceMappingURL=commonHelpers.js.map
